dfinity/ic-hs

default.nix
ic-hs.cabal

it fails with
```
/nix/store/cdbsfljc8m900axs37fab7gnp2y1dksn-binutils-2.31.1/bin/ld: /nix/store/x0ybqvkk6h6x8mhsy5gghplsfvammq6q-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-musl/9.3.0/crtbeginT.o: relocation R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making a shared object
/nix/store/cdbsfljc8m900axs37fab7gnp2y1dksn-binutils-2.31.1/bin/ld: /nix/store/x0ybqvkk6h6x8mhsy5gghplsfvammq6q-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-musl/9.3.0/crtend.o: relocation R_X86_64_32 against `.ctors' can not be used when making a shared object; recompile with -fPIC
/nix/store/cdbsfljc8m900axs37fab7gnp2y1dksn-binutils-2.31.1/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
`cc' failed in phase `Linker'. (Exit code: 1)
builder for …
```

Do not build the library in musl

---

src/ic-ref-run.hs

ic-ref-run: Pretty print candid values without type table

---

.github/workflows/test.yml

and restrict build-on-push to master, to not run the job twice on PRs
from within the repo.

Github actions: Run nix action on pull requests, too

---

nix/sources.json

in #30 we tracked a PR against nixpkgs, which isn't very stable (e.g. if
it gets force-pushed to, it may break this repository). The changes we
are trying to include are still not in nixpkgs master, but they are
closer already, on the `haskell-upgrades` branch. So track that, until
it is merged into `master` (via https://github.com/NixOS/nixpkgs/pull/138596)

Nix: Track haskell-upgrades

---

src/IC/Canister/Imp.hs
src/IC/Test/Spec.hs
src/IC/Test/Universal.hs
universal-canister/src/api.rs
universal-canister/src/main.rs

The stub will be replaced with a proper implementation once its semantics gets clarified.

Create a stub of performance_counter

---

nix/sources.json

with https://github.com/NixOS/nixpkgs/pull/138596 merged into `master`
we can track that again, which is cleaner. This is a follow-up to
https://github.com/dfinity/ic-hs/pull/37

nix: Track nixpkgs master again

---

.mergify.yml

this adds a mergify configuration to the repo, fixing #33.
TL;DR: Label a PR with `automerge-squash` and it will be merged once
approved an green. Also, mergify will update out-of-date branches as
`master` changes.
It is based on the `.mergify.yaml` from Motoko, but omitting the “fancy”
features (e.g. approving changelog changes and dependency bumps). We can
add them when and if we add auto dependency bumping, but we don’t have
that many dependencies, so maybe not needed.

Configure mergify

---

src/IC/Test/Spec.hs

these should be treated like calls to non-existant canisters, and it
doesn’t hurt to test that

ic-ref-test: Test inter-canister calls to user’s principals

---

ic-hs.cabal
src/IC/Canister.hs
src/IC/Canister/Imp.hs
src/IC/Certificate/Value.hs
src/IC/Crypto/WebAuthn.hs
src/IC/HTTP/RequestId.hs
src/IC/Ref.hs
src/IC/Test/Spec.hs
src/IC/Utils.hs

this is a reimplementation of @jwiegley’s #53; his PR gave me many ideas
that I felt would be very tedious and impolite to convey through prose
review, so I just wrote down how I would do it. I hope this achieves the
level of declaratively that we aim for (by moving plumbing code into
other modules, for example, and by having more precise types.)
In addition to #53, this performs more module validation, and adds
further tests, and fixes a bug where deleted canisters still show up in
the state tree (probably worth refactoring to avoid such bugs, but not
in this PR).

[VER-1123] Implement metadata access

---

ic-hs.cabal

The module `IC.Crypto.WebAuthn` uses `Aeson.parseFail` which was only
introduced in
[1.4.7](https://github.com/haskell/aeson/blob/master/changelog.md#1470)

Set lower bound on aeson

---

default.nix
src/IC/Canister/Imp.hs
src/IC/Test/Agent.hs
src/IC/Test/Spec.hs
src/IC/Test/Universal.hs
universal-canister/src/api.rs
universal-canister/src/main.rs

Following up on our discussion regarding the multivalue target feature support, we have decided to update the experimental System Api and not rely on this feature anymore.
This MR updates the tests according to the Public Spec.

Update system API for 128 bit cycles tests

---

.github/workflows/release.yml

especially during maintenance work like in #64 it is useful to keep
running the test on one arch even if the other is failing.

Github Actions: Disable fast failing

---

README.md
src/IC/Ref.hs
src/IC/Test/Agent.hs
src/IC/Test/Spec.hs

This allows the test driver to withhold the response to a message, and
control when they are released, in order to produce situations with
outstanding call contexts.
In an ideal world (from our pov), we could instrument and control the
system's scheduler this way, but we can't. So instead, we use some tricks.
Ideally, the details of this trick are irrelevant to the users of this
function (yay, abstraction), and if we find better tricks, we can swap them
out easily. We'll see if that holds water.
One problem with this approach is that a test failure could mean that the
system doesn't pass the test, but it could also mean that the system has a
bug that prevents this trick from working, so take care.
The current trick is: Create a canister (the "stopper"). Make it its own
controller. Tell …

ic-ref-test: Test stopping state

---

ic-hs.cabal
src/IC/Canister.hs
src/IC/Test/Spec.hs

This change adds support for installing gzip-compressed modules
as specified in https://github.com/dfinity/interface-spec/pull/11

feat: support gzip-compressed canister modules

---

.mergify.yml

Mergify changed their `commit_message` option to `commit_message_template`. 
See: https://docs.mergify.com/actions/queue/#id2

fix: mergify config

---

.github/workflows/release.yml
README.md

GitHub Actions Runners only have 7GB of memory which is proving to be too small to built ic-hs. So instead of building nix derivations on a runner locally we configure the runner to build derivations remotely on [nixbuild.net](https://nixbuild.net/).
The above requires access to a private SSH key, which is used to authenticate with nixbuild.net. This key is not accessible on PRs originating from forks because that would allow leaking the key. For those PRs we don't configure nixbuild.net as a remote builder and build locally instead.

Use nixbuild.net as a remote nix builder on CI

---

src/IC/Debug/JSON.hs
src/IC/HTTP/Request.hs
src/IC/Ref.hs
src/IC/Serialise.hs
src/IC/Test/Agent.hs
src/IC/Test/Spec.hs
src/IC/Types.hs
src/ic-ref-run.hs

This change relaxes the ic-ref-test suite to allow optional "error_code"
field in query responses and in request statuses as described in
https://github.com/dfinity/interface-spec/pull/38

feat: allow optional "error_code" field in responses

---

src/IC/Canister/Imp.hs
src/IC/Test/Spec.hs
src/IC/Test/Universal.hs
universal-canister/src/api.rs
universal-canister/src/main.rs

This change fixes the signature of "ic0.performance_counter" system API
to agree with the latest interface spec.
See
https://github.com/dfinity/interface-spec/blob/f5fc17b4e2ac0e930b6a29a3f25226b3c4b56a6f/spec/ic0.txt#L62

fix: performance_counter signature

---

.github/workflows/release.yml

We need to update the ic-ref that we bundle with the SDK to one that supports `ic0.performance_counter`
Reverts dfinity/ic-hs#82

Revert ".github/workflows/release.yml: disable MacOS builds in release job"

---

src/IC/Ref.hs
src/IC/Test/Spec.hs

According to [Interface Spec](https://github.com/dfinity/interface-spec/pull/87), a request id must have length of 32 bytes. Hence, a read request for the status of a request whose id does not have this length is a malformed read state request that should be rejected with 4xx.

Request IDs must be 32 bytes in length.

---

src/IC/Test/Spec.hs

This is a regression test of a buggy replica change that passed the remaining tests from the "wrong effective canister id" group.

add test of wrong effective canister id in read state

---

README.md
ic.did
src/IC/Ref.hs
src/IC/Test/Agent/Calls.hs
src/IC/Test/Spec.hs
src/IC/Test/Universal.hs
universal-canister/Cargo.lock
universal-canister/Cargo.toml
universal-canister/src/main.rs

This PR makes the following changes:
- add context to transform for canister http_request and update the canister http_request fee accordingly
- the caller of transform function for canister http_request is the management canister
- add tests for the above two changes
The corresponding Interface Spec can be found [here](https://github.com/dfinity/interface-spec/pull/96).

add transform context for canister http_request

---

src/IC/Test/Agent.hs

Currently, HTTP error message are trimmed like this:
```
src/IC/Test/Agent.hs:723:
Status 400 is not 2xx:
Specified ingress_expiry not within expected range:
Minimum allowed expiry: 2022-11-08 17:30:48.509933047 UTC
Maximum allowed expiry: 2022-11-08 17:36:18.509933047 UTC
Provided expiry:        2022-11-
```
Increasing the threshold should allow us to see the entire HTTP error message.

display more characters in HTTP error messages

---

ic-hs.cabal
nix/generated/ic-hs.nix
src/IC/Test/Agent.hs
src/IC/Test/Spec.hs

Querying the balance of a canister with installed code twice in a row might not yield the same result because the canister is charged for resource usage:
```
cycles API - backward compatibility
canister_cycle_balance = canister_cycle_balance128 for numbers fitting in 64 bits: FAIL (10.40s)
src/IC/Test/Agent.hs:666:
expected: 1152921502679711556
but got: 1152921502680301640
```
This PR fixes the above test by querying balance and balance128 within the same query.

query balance and balance128 within the same query

---

src/IC/Canister/Imp.hs
src/IC/Ref.hs
src/IC/Test/Spec.hs
src/IC/Test/Universal.hs
src/IC/Types.hs
universal-canister/src/api.rs
universal-canister/src/lib.rs
universal-canister/src/main.rs

The name "canister state counter" could be confusing because the counter is not incremented upon every change of the canister state. Hence, we agreed to rename it to "canister version".

rename canister state counter to canister version

---

ic-hs.cabal
nix/generated/ic-hs.nix
src/IC/HTTP.hs
src/ic-ref-run.hs
src/ic-ref.hs

Currently, system tasks (heartbeat and global timer) are only triggered upon receiving an HTTP request. This MR adds a new execution thread that periodically triggers these tasks every second.

run system tasks periodically

---

src/IC/Ref.hs
src/IC/Test/Spec.hs

Calls to stopping/stopped canisters should not be rejected with an HTTP error (see [API Request submission](https://ic-interface-spec.netlify.app/#_api_request_submission) which can succeed even if the canister is not running). Instead, the request should go through the states received, processing, and finally rejected.

do not return an HTTP error for calls to stopping/stopped canisters

---

src/IC/Ref.hs

This PR fixes a regression due to dropping `rejectAsCanister`: `dfx` expects reject code 5 when installing code on non-empty canister or upgrading an empty canister. This is in line with the [starvation](https://ic-interface-spec.netlify.app/#rule-starvation) transition that would be taken in this case and the description of the reject code 3: "DESTINATION_INVALID (3): Invalid destination (e.g. canister/account does not exist)" that is not applicable in this case.

fix reject code of installing on (non-)empty canister

---

.github/workflows/release.yml
default.nix

This MR fixes the error
```
dyld[2382]: Library not loaded: '@executable_path/libz.1.2.12.dylib'
Referenced from: '/Users/runner/.cache/dfinity/versions/0.12.1+rev36.7883e5aa/ic-ref'
Reason: tried: '/Users/runner/.cache/dfinity/versions/0.12.1+rev36.7883e5aa/libz.1.2.12.dylib' (no such file), '/usr/local/lib/libz.1.2.12.dylib' (no such file), '/usr/lib/libz.1.2.12.dylib' (no such file)
```
observed on macOS when using our artifact.

fix macOS artifacts

---

src/IC/Constants.hs
src/IC/Ref.hs
src/IC/Test/Agent/Calls.hs
src/IC/Test/Options.hs
src/IC/Test/Spec.hs
src/IC/Types.hs
src/IC/Utils.hs
src/ic-ref-run.hs
src/ic-ref-test.hs
src/ic-ref.hs
src/unit-tests.hs

The replica implementation scales the cost of calls as follows:
```
// Scale cycles cost according to a subnet size.
fn scale_cost(&self, cycles: Cycles, subnet_size: usize) -> Cycles {
match self.use_cost_scaling_flag {
false => cycles,
true => (cycles * subnet_size) / self.config.reference_subnet_size,
}
}
```
where `self.config.reference_subnet_size` is set to
```
/// Default subnet size which is used to scale cycles cost according to a subnet replication factor.
///
/// All initial costs were calculated with the assumption that a subnet had 13 replicas.
/// IMPORTANT: never set this value to zero.
const DEFAULT_REFERENCE_SUBNET_SIZE: usize = 13;
```
Recently, `self.use_cost_scaling_flag` was enabled and thus this PR implements cycle cost scaling based on subnet size also in the …

scale cycle cost of http_request calls based on subnet size

---

src/IC/Ref.hs
src/IC/Test/Spec.hs

Canister `http_requests` management canister calls should be charged based on the target subnet executing the call. This subnet is only different from the caller's subnet if the call is a subnet message with an explicit subnet ID provided by the caller. Adding support for subnet messages with an explicit subnet ID provided by the caller makes it necessary to adjust the behavior of canister `http_request` calls in terms of charging cycles.

charge canister http_request based on target subnet

---

.github/workflows/release.yml

This should decrease the size of the ic-ref-test artifact by omitting the ic-ref binary.

omit ic-ref binary in ic-ref-test artifact

---

src/IC/Canister/Imp.hs
src/IC/Test/Spec.hs

Canister Timers are allowed in post-upgrade and init and it is easy to assume that they are also okay in pre-upgrade.
Picked up from https://github.com/dfinity-berestovskyy/ic-hs/tree/andriy/run-509-timers-in-pre-upgrade because CI fails on PRs from forks.

RUN-509: Enable Canister Timers in pre-upgrade

---

src/IC/Test/Spec.hs
src/IC/Test/Universal.hs
universal-canister/src/api.rs
universal-canister/src/lib.rs
universal-canister/src/main.rs

This PR makes the following changes:
- sync universal_canister with IC monorepo
- add one-way calls to universal_canister
- add tests for canister timer in post-upgrade on stopped and stopping canisters to cover a regression in mainnet implementation

add test for timer in post-upgrade on stopped and stopping canister

---

src/IC/CBOR/Utils.hs
src/IC/Id/Forms.hs
src/IC/Id/Fresh.hs
src/IC/Test/Agent.hs
src/IC/Test/Spec.hs
src/IC/Test/Spec/Utils.hs

According to Interface Spec: Delegations are scoped, i.e., they indicate which set of canister principals the delegatee subnet may certify for. This set can be obtained from a delegation `d` using `lookup(["subnet",d.subnet_id,"canister_ranges"],d.certificate)`, which must be present, and is encoded as follows:
```
canister_ranges = tagged<[*canister_range]>
canister_range = [principal principal]
principal = bytes .size (0..29)
tagged<t> = #6.55799(t) ; the CBOR tag
```

implement canister range checks in ic-ref-test

---

src/IC/Ref.hs
src/IC/Test/Agent.hs
src/IC/Test/Spec.hs

This MR implements the following fixes of `ic-ref`:
- implement access control for `read_state` requests according to [Interface Spec](https://ic-interface-spec.netlify.app/#http-read-state)
- `create_canister` cannot be called via ingress message

fix conditions on read_state requests

---

src/IC/Test/Agent.hs

The error message
```
Specified ingress_expiry not within expected range:
Minimum allowed expiry: 2023-02-01 20:32:37.020911897 UTC
Maximum allowed expiry: 2023-02-01 20:38:07.020911897 UTC
Provided expiry:        2023-02-
```
does not allow one to tell how far off the provided expiry is. This PR is supposed to fix that.

increase error msg length limit

---

.github/workflows/release.yml

The GitHub darwin runners only have 14GB of memory. However the `coverage` job requires 17GB which means those machines start swapping which grinds exection to a halt eventually timing out the job.
Since we only care about building the `ic-ref-dist` job on darwin we only run the problematic `coverage` job on linux.

.github/workflows/release.yml: skip coverage job on darwin

---

src/IC/Test/Spec.hs

The two "Multiple controllers" tests take very long in gitlab CI:
```
Feb 27 23:09:14.285 INFO[rs/tests/src/driver/new/group.rs:996:17] [test|StdOut]         Multiple controllers (provisional):                                                OK (231.36s)
Feb 27 23:09:14.299 INFO[rs/tests/src/driver/new/group.rs:996:17] [test|StdOut]         Multiple controllers (aaaaa-aa):                                                   FAIL (226.44s)
```
This PR split the tests into multiple smaller ones to reduce their maximum running time. This should reduce the flakiness of these tests/

split Multiple controllers tests

---

src/IC/Ref.hs
src/IC/Test/Spec.hs

The Interface Spec says
```
Read state requests containing many requested paths might be rejected with a 4xx HTTP status code.
NOTE
The Internet Computer blockchain mainnet might reject read state requests that request more than 1 path with prefix /request_status/<request_id>.
```
This PR enforces the bound of at most one path with prefix `/request_status/<request_id>` and updates the test suite so that we can enforce the same limit in the mainnet implementation.

can request at most one request_status path in read_state

---

src/IC/HTTP/Request.hs
src/IC/Test/Spec.hs

Interface Spec says: "The delegation field, if present, must not contain more than four delegations."
This MR implements the above sentence in the reference implementation and its test suite.

check the number of delegations in sender_delegation

---

httpbin-rs/src/main.rs
src/IC/Test/Spec/HTTP.hs

This MR removes the keep-alive connection header from httpbin response as the httpbin server does not persist any connections.

do not include keep-alive header in httpbin response

---

.github/workflows/release.yml
default.nix

The command `nix-build-uncached` does not seem to run the actual builds, so this PR replaces `nix-build-uncached` by `nix-build`.

drop nix-build-uncached

---

src/IC/Test/Agent.hs

This MR increases `ingress_expiry` in the reference test suite and thus should help with test flakiness due to errors of the form
```
2023-05-17 09:40:36.544 INFO[test:StdOut]         src/IC/Test/Spec.hs:2424:
2023-05-17 09:40:36.544 INFO[test:StdOut]         Status 400 is not 2xx
2023-05-17 09:40:36.544 INFO[test:StdOut]         Specified ingress_expiry not within expected range:
2023-05-17 09:40:36.544 INFO[test:StdOut]         Minimum allowed expiry: 2023-05-17 09:40:36.454146577 UTC
2023-05-17 09:40:36.544 INFO[test:StdOut]         Maximum allowed expiry: 2023-05-17 09:46:06.454146577 UTC
2023-05-17 09:40:36.544 INFO[test:StdOut]         Provided expiry:        2023-05-17 09:40:34.111518055 UTC
2023-05-17 09:40:36.544 INFO[test:StdOut]         Local replica time:     2023-05-17 …
```

increase ingress_expiry in reference test suite

---

httpbin-rs/src/main.rs
src/IC/Test/Spec/HTTP.hs

The header `Connection: close` is supposed to prevent the client from keeping idle connections alive as they're not being kept alive on the httpbin server.

add Connection: close header to httpbin

---

default.nix
nix/default.nix
universal-canister/src/main.rs

We bump Rust version to 1.66.1 and thus can fully sync universal-canister code with the IC repo.

sync universal-canister with IC repo

---

src/IC/HTTP.hs
src/IC/Ref.hs

**Changes**
This PR makes the following changes:
- run steps of the IC on a single thread with `yield` in between consecutive steps (given that every step needs to acquire a lock on the IC state, we don't gain much by having tight loops running steps of the IC on multiple threads)
- run system tasks (heartbeats and timers) whenever an ingress message result (reply/reject) is put into the certified state (as opposed to when the user submits the request which decreases the latency of the 202 HTTP response to the user request)
**Benchmarks**
base-line (a1b3f6706c33a40f1b7faa65a9652b3ddf39d1a6)
ic-ref-test: 410.51 s
ic-nns-init: 14.3 s
this PR
ic-ref-test: 409.86 s
ic-nns-init: 11.6 s

decrease number of threads and request submission latency

---

src/IC/Canister.hs
src/IC/Serialise.hs

This PR fixes an issue with snapshotting IC states with canisters having compressed WASM modules. Currently, their compressed WASM modules are attempted to be parsed by Winter which fails because Winter expects the decompressed WASM. Hence, this PR decompresses all WASM modules decoded from a snapshot before parsing them with Winter.

fix decoding compressed WASM modules during snapshotting

---

nix/sources.json

requested by @ggreif: to have a common (last on branch `22.11`) revision for `ic-hs` and `motoko`. (`22.11` is deprecated with the advent of `23.05`.)

bump nixpkgs to eaf03591711b46d21abc7082a8ebee4681f9dbeb

---

httpbin-rs/src/main.rs
src/IC/Test/Spec/HTTP.hs

This MR implements changes necessary to make the implementation of httpbin use a high-level server API (e.g., axum) that always includes a date header in its responses and produces lower-case http header names.

add date header to httpbin responses and make http header names lower-case

---

src/IC/Debug/JSON.hs

The JSON debug state exposed at `http://localhost:<port>` is intended for manual inspection in a web browser and thus we should trim long blobs that slow down loading the JSON file in the web browser without facilitating human readability.

trim long blobs in json debug state

---

ic-hs.cabal
src/IC/Canister.hs
src/IC/Ref.hs
src/IC/Test/Spec.hs
src/IC/Test/Spec/CanisterVersion.hs
src/IC/Test/Spec/Timer.hs
src/IC/Test/Spec/Utils.hs

The replica implementation increments the canister version upon every successful message execution so let’s do the same in the reference implementation and tighten its test suite.

bump canister version upon successful message execution and tighten tests

---

src/IC/Ref.hs
src/IC/Test/Spec.hs

This PR implements this spec [PR](https://github.com/dfinity/interface-spec/pull/168).

deleted call contexts prevent canister from stopping (again)

---

src/IC/Test/Spec/CanisterHistory.hs

Replica implementation requires cycles to be attached to a canister creation call on an app subnet. This PR adjusts the canister history test accordingly.

attach cycles to canister creation in canister history tests

---

default.nix

The performance of `ic-ref` degrades the more canisters are deployed on `ic-ref`. Hence, this PR speeds up tests by restarting `ic-ref` between consecutive `ic-ref-test` invokations.

restart ic-ref in tests

---

src/IC/Constants.hs
src/IC/Utils.hs

Update `http_request` fee to the new proposed formula:
```
(3M + 60K * n + 400 * request_size + 800 * max_response_bytes) * n
```
where `n` is the subnet size.
Corresponding replica MR: https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/13150

update http_request fee calculation

---

src/IC/Test/Agent.hs

This PR should address ic-ref-test flakiness of the form:
```
2023-07-03 12:15:17.159 INFO[test:StdOut]         Exception: HttpExceptionRequest Request {
2023-07-03 12:15:17.159 INFO[test:StdOut]           host                 = "[2a0b:21c0:4003:2:5014:5eff:fe29:8571]"
2023-07-03 12:15:17.159 INFO[test:StdOut]           port                 = 8080
2023-07-03 12:15:17.159 INFO[test:StdOut]           secure               = False
2023-07-03 12:15:17.159 INFO[test:StdOut]           requestHeaders       = [("Content-Type","application/cbor")]
2023-07-03 12:15:17.159 INFO[test:StdOut]           path                 = "/api/v2/canister/rwlgt-iiaaa-aaaaa-aaaaa-cai/call"
2023-07-03 12:15:17.159 INFO[test:StdOut]           queryString          = ""
2023-07-03 12:15:17.159 INFO[test:StdOut] …
```

increase HTTP response timeout in ic-ref-test

---

bin/ic-ref-test.hs
src/IC/Test/Agent.hs
src/IC/Test/Options.hs

We need to use self-signed certificates in BNs in pre-master system tests and thus this PR makes it possible to configure `ic-ref-test` to allow such certificates.

allow self-signed certificates in ic-ref-test

---

src/IC/Ref.hs
src/IC/Ref/Types.hs
src/IC/Test/Agent/UserCalls.hs
src/IC/Test/Spec.hs

The effective canister ID in the URL of every request (update, query, read state request) must be contained in the canister ranges of a subnet (so that the request can be properly routed to that subnet by the BN in the mainnet implementation). This PR checks that condition in the reference implementation, fixes a test that did not satisfy the condition, and also adds tests that explicitly test for that condition.
Note. The conditions on effective canister IDs are specified in this [section](https://ic-interface-spec.netlify.app/docs/#http-effective-canister-id) of the Interface Specification and should be updated, too.

check effective canister id against subnets' canister ranges

---

src/IC/Test/Spec.hs
src/IC/Test/Spec/Utils.hs

BN query caching can make compliance tests flaky by caching query results with the same arguments for up to 1s. This PR addresses that source of flakiness by making query arguments in tests pairwise distinct.

make query arguments in tests pairwise distinct to prevent BN query caching

---

src/IC/Test/Agent.hs

When using BNs in the IC topology of system tests, we need to sync node height even before making an update call because the `inspect_message` call (that precedes the actual replicated update method execution) is executed non-replicated and thus its outcome depends on all nodes being up-to-date.

sync node height before making an update call in compliance tests
